In [1]:
import os
from maze_env import Maze
from utility import RL
import time

In [2]:
# def onKeyPress(event):
#     is_terminate = False
#     if (event.char == "w"):
#         is_terminate, reward = env.take_action(0, show_animate=True)
#     elif (event.char == "d"):
#         is_terminate, reward = env.take_action(1, show_animate=True)
#     elif (event.char == "s"):
#         is_terminate, reward = env.take_action(2, show_animate=True)
#     elif (event.char == "a"):
#         is_terminate, reward = env.take_action(3, show_animate=True)
#     elif (event.char == "q"):
#         env.destroy()
#     if (is_terminate):
#         env.reset()

In [3]:
# if __name__ == "__main__":
env = Maze()
rl = RL(env)
print('{0}x{1}, act_space = {2}'.format(env.MAZE_Limit[0],env.MAZE_Limit[1], len(env.action_space)))
# env.bind('<KeyPress>', onKeyPress)
# env.mainloop()

4x4, act_space = 4


# DP Prediction

In [4]:
rl.DP.iteration(update = 10)

9 [[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]


# model-free MC

In [5]:
rl.MF.iteration(n_episode = 3000,  model = "MC")

The model is MC
Value
 [[ 0.         -5.31527834 -7.14043398 -7.58387295]
 [-5.30748432 -6.62942608 -7.18780912 -7.20460604]
 [-7.07593468 -7.10241449 -6.47110493 -5.20464986]
 [-7.70234096 -6.96732699 -4.95668986  0.        ]]
--------------------------



# model-free TD(0)

In [6]:
rl.MF.iteration(n_episode = 3000,  model = "TD_0")

The model is TD_0
Value
 [[ 0.         -1.31071428 -4.37036657 -6.73322409]
 [-3.06414001 -5.08815727 -5.9640618  -5.73861783]
 [-5.81240388 -6.69393045 -4.98142397 -2.08774669]
 [-7.05168258 -7.44907119 -2.35094995  0.        ]]
--------------------------



# model-free TD(n)

In [7]:
rl.MF.iteration(n_episode = 3000,  model = "TD_n")

The model is TD_n
Value
 [[ 0.         -3.59046699 -5.27496271 -4.78902523]
 [-1.91607915 -4.47586466 -8.9723571  -6.25849089]
 [-8.12147394 -5.52442398 -4.92790556 -3.53889553]
 [-5.38258517 -3.32380147 -4.2082651   0.        ]]
--------------------------



# model-free TD(lambda)

In [8]:
rl.MF.iteration(n_episode = 3000,  model = "TD_lambda")

The model is TD_lambda
Value
 [[ 0.         -2.77943411 -7.10213333 -5.46885787]
 [-5.43597214 -4.33308475 -4.94882853 -3.70012434]
 [-5.42081258 -4.08995379 -2.77324518  0.46872652]
 [-4.87893364 -2.4161529  -0.84774228  0.        ]]
--------------------------



# testing field

In [9]:
import numpy as np
import time
a = np.array([1,2,3,4,5])

In [10]:
# t = time.time()
np.logspace(start=1,stop=len(a),num=len(a),endpoint=True,base=2)/2
# print(time.time()-t)

array([ 1.,  2.,  4.,  8., 16.])

In [11]:
# t = time.time()
np.array([2**i for i in range(len(a))])
# print(time.time()-t)

array([ 1,  2,  4,  8, 16])