In [1]:
import os
from maze_env import Maze
from utility import RL
import time
import numpy as np

In [2]:
# def onKeyPress(event):
#     is_terminate = False
#     if (event.char == "w"):
#         is_terminate, reward = env.take_action(0, show_animate=True)
#     elif (event.char == "d"):
#         is_terminate, reward = env.take_action(1, show_animate=True)
#     elif (event.char == "s"):
#         is_terminate, reward = env.take_action(2, show_animate=True)
#     elif (event.char == "a"):
#         is_terminate, reward = env.take_action(3, show_animate=True)
#     elif (event.char == "q"):
#         env.destroy()
#     if (is_terminate):
#         env.reset()

In [3]:
# if __name__ == "__main__":
env = Maze()
rl = RL(env)
print('{0}x{1}, act_space = {2}'.format(env.MAZE_Limit[0],env.MAZE_Limit[1], len(env.action_space)))
# env.bind('<KeyPress>', onKeyPress)
# env.mainloop()

4x4, act_space = 4


# DP Prediction

In [4]:
rl.DP.iteration(update = 10)

9 [[ 0. -1. -2. -3.]
 [-1. -2.  0. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]


# model-free MC

In [5]:
rl.MF.iteration(n_episode = 3000,  model = "MC")

The model is MC


In [6]:
Avalue = rl.MF.Avalue
final_policy = rl.MF.policy
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[0],env.MAZE_Limit[1]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[0],env.MAZE_Limit[1]))

[Expect] State-value
 [[ 0.         -5.06419824 -6.87033052 -7.30079733]
 [-5.0930815  -6.33360063  0.         -6.8884636 ]
 [-7.03745436 -6.99597666 -6.236216   -5.05161999]
 [-7.55059119 -6.97033549 -5.12569322  0.        ]]
[Max] Action to State-value
 [[ 0.         -1.         -5.65364303 -7.02999837]
 [-1.         -5.60460782  0.         -5.4671332 ]
 [-5.69219769 -6.60886073 -5.56379339 -1.        ]
 [-7.29583771 -5.6028993  -1.          0.        ]]


# model-free TD(0)

In [7]:
#hyper parameters
rl.MF.gamma = 0.9 # discount factor
rl.MF.lamb = 0.9 # parameter of sarsa
rl.MF.alpha = 0.5 # step size

In [8]:
rl.MF.iteration(n_episode = 3000,  model = "TD_0")

The model is TD_0


In [9]:
Avalue = rl.MF.Avalue
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[  0.     -7.75   -7.975  -6.355]
 [ -7.75  -10.      0.     -7.975]
 [ -7.975 -10.    -10.     -7.75 ]
 [ -6.355  -7.975  -7.75    0.   ]]
[Max] Action to State-value
 [[  0.    -1.    -1.9   -2.71]
 [ -1.   -10.     0.    -1.9 ]
 [ -1.9  -10.   -10.    -1.  ]
 [ -2.71  -1.9   -1.     0.  ]]


# model-free TD(n)

In [10]:
rl.MF.iteration(n_episode = 3000,  model = "TD_n")

The model is TD_n


In [11]:
Avalue = rl.MF.Avalue
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[ 0.         -4.82790569 -7.15798409 -7.03026271]
 [-5.81728287 -6.12045627  0.         -6.44420516]
 [-7.5350811  -6.17118395 -5.76243384 -5.33528647]
 [-7.14822229 -6.81877635 -4.49658247  0.        ]]
[Max] Action to State-value
 [[ 0.         -1.         -4.49787414 -5.59535308]
 [-1.         -4.10768668  0.         -4.89757636]
 [-6.44725977 -4.74981201 -3.6859133  -1.        ]
 [-6.39123152 -3.63486322 -1.          0.        ]]


# model-free TD(lambda)

In [12]:
rl.MF.iteration(n_episode = 1000,  model = "TD_lambda")

The model is TD_lambda


In [13]:
Avalue = rl.MF.Avalue
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[  0.          -7.7500723   -7.97510877  -6.35506829]
 [ -7.74995085 -10.00024007   0.          -7.97469045]
 [ -7.97445178  -9.99973195  -9.99950401  -7.74977264]
 [ -6.35496893  -7.97529965  -7.75019705   0.        ]]
[Max] Action to State-value
 [[ 0.         -1.         -1.90000732 -2.70993973]
 [-1.         -9.99982572  0.         -1.90013046]
 [-1.89999096 -9.99820752 -9.99808822 -1.        ]
 [-2.7098692  -1.89998324 -1.          0.        ]]


# model-free Control MC

In [14]:
rl.MF.iteration(n_episode = 3000,  model = "MC", control = True)

The model is MC


In [15]:
Avalue = rl.MF.Avalue
final_policy = rl.MF.policy
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("Policy\n",np.argmax(final_policy,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[ 0.         -1.9458272  -3.59381186 -4.42146576]
 [-1.95964657 -3.23000444  0.         -3.35976955]
 [-3.38394308 -3.88066404 -3.13506266 -1.95379218]
 [-4.26116157 -3.38337464 -1.95408934  0.        ]]
[Max] Action to State-value
 [[ 0.         -1.         -2.81241376 -4.05163105]
 [-1.         -2.83499715  0.         -2.77872967]
 [-2.71381137 -3.80841631 -2.77603983 -1.        ]
 [-4.03985869 -2.69834365 -1.          0.        ]]
Policy
 [[0 3 3 3]
 [0 0 0 2]
 [0 1 1 2]
 [0 1 1 0]]


# model-free Control Sarsa(lambda)

In [16]:
rl.MF.iteration(n_episode = 30000,  model = "TD_lambda", control = True)

The model is TD_lambda


In [17]:
Avalue = rl.MF.Avalue
final_policy = rl.MF.policy
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("Policy\n",np.argmax(final_policy,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[  0.          -4.35593318  -4.92463708  -4.46907521]
 [ -4.37574753 -10.00271447   0.          -4.91395736]
 [ -4.93737937 -10.00139913  -9.99968137  -4.33915167]
 [ -4.53238164  -4.93911043  -4.37495103   0.        ]]
[Max] Action to State-value
 [[ 0.         -1.         -1.89948633 -2.70936706]
 [-1.         -9.99999667  0.         -1.89898173]
 [-1.89990822 -9.99939441 -9.99922115 -1.        ]
 [-2.70988597 -1.89999476 -1.          0.        ]]
Policy
 [[0 3 3 3]
 [0 3 0 2]
 [0 3 3 2]
 [1 1 1 0]]


# testing field

In [18]:
import time
a = np.array([1,2,3,4,5])

In [19]:
# t = time.time()
np.logspace(start=1,stop=len(a),num=len(a),endpoint=True,base=2)/2
# print(time.time()-t)

array([ 1.,  2.,  4.,  8., 16.])

In [20]:
# t = time.time()
np.array([2**i for i in range(len(a))])
# print(time.time()-t)

array([ 1,  2,  4,  8, 16])