In [1]:
import os
from maze_env import Maze
from rl_algo import RL
import time
import numpy as np

In [2]:
# def onKeyPress(event):
#     is_terminate = False
#     if (event.char == "w"):
#         is_terminate, reward = env.take_action(0, show_animate=True)
#     elif (event.char == "d"):
#         is_terminate, reward = env.take_action(1, show_animate=True)
#     elif (event.char == "s"):
#         is_terminate, reward = env.take_action(2, show_animate=True)
#     elif (event.char == "a"):
#         is_terminate, reward = env.take_action(3, show_animate=True)
#     elif (event.char == "q"):
#         env.destroy()
#     if (is_terminate):
#         env.reset()

In [3]:
# if __name__ == "__main__":
env = Maze()
rl = RL(env)
print('{0}x{1}, act_space = {2}'.format(env.MAZE_Limit[0],env.MAZE_Limit[1], len(env.action_space)))
# env.bind('<KeyPress>', onKeyPress)
# env.mainloop()

4x4, act_space = 4


# DP Prediction

In [4]:
rl.DP.iteration(update = 10)

9 [[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10.  0. 10. 10.]
 [10. 10. 10. 10.]]


# model-free MC

In [5]:
rl.MF.iteration(n_episode = 3000,  model = "MC")

The model is MC


In [6]:
Avalue = rl.MF.Avalue
final_policy = rl.MF.policy
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[0],env.MAZE_Limit[1]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[0],env.MAZE_Limit[1]))

[Expect] State-value
 [[0.62585038 0.78608358 1.11887695 1.40881278]
 [0.71809319 0.94859475 1.74725861 2.40958605]
 [0.88380037 0.         3.35059863 4.87514551]
 [1.43519173 2.63662704 5.03536485 0.        ]]
[Max] Action to State-value
 [[ 0.74486238  1.01670766  1.57809469  2.08595458]
 [ 0.88882886  1.64393913  2.99308136  4.62812882]
 [ 1.31190107  0.          4.37804437 10.        ]
 [ 2.38090278  4.48191235 10.          0.        ]]


# model-free TD(0)

In [7]:
#hyper parameters
rl.MF.gamma = 0.9 # discount factor
rl.MF.lamb = 0.9 # parameter of sarsa
rl.MF.alpha = 0.5 # step size

In [8]:
rl.MF.iteration(n_episode = 3000,  model = "TD_0")

The model is TD_0


In [9]:
Avalue = rl.MF.Avalue
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[0.53831762 0.5930581  1.07821956 1.61749789]
 [0.68039485 0.75881308 1.7823823  2.63708201]
 [0.61759477 0.         4.22406872 4.17001913]
 [1.27088779 3.83802703 6.10709242 0.        ]]
[Max] Action to State-value
 [[ 0.60016359  0.73449873  2.04121138  3.38715763]
 [ 0.79580631  1.15641876  4.09757531  6.40276973]
 [ 0.82562708  0.          7.00166838 10.        ]
 [ 1.75170987  6.93635633 10.          0.        ]]


# model-free TD(n)

In [10]:
rl.MF.iteration(n_episode = 3000,  model = "TD_n")

The model is TD_n


In [11]:
Avalue = rl.MF.Avalue
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[0.38981509 1.13580878 1.38239575 0.7444338 ]
 [0.75308717 1.68967572 2.61253151 0.93474725]
 [0.64518846 0.         4.30474857 4.66936251]
 [1.38391211 1.74190399 5.36915781 0.        ]]
[Max] Action to State-value
 [[ 0.59742621  1.93232227  3.05994302  2.13102189]
 [ 2.04032362  5.08028168  6.10415251  1.6254683 ]
 [ 1.20857975  0.          7.88567047 10.        ]
 [ 3.16214294  2.95506125 10.          0.        ]]


# model-free TD(lambda)

In [12]:
rl.MF.iteration(n_episode = 1000,  model = "TD_lambda")

The model is TD_lambda


In [13]:
Avalue = rl.MF.Avalue
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[0.38272982 0.55181252 0.97123525 0.81562638]
 [0.60358107 0.62177802 1.82873997 2.51663787]
 [0.67633124 0.         3.27005579 6.92154598]
 [1.03422086 2.22300168 5.3591418  0.        ]]
[Max] Action to State-value
 [[ 0.46806593  0.63559816  2.40805121  1.38313305]
 [ 0.95594241  0.79426336  4.57962842  3.45591471]
 [ 1.11137687  0.          8.04985471 10.54053963]
 [ 1.60352294  3.74264007 10.          0.        ]]


# model-free Control MC

In [14]:
rl.MF.iteration(n_episode = 1000,  model = "MC", control = True)

The model is MC


In [15]:
Avalue = rl.MF.Avalue
final_policy = rl.MF.policy
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("Policy\n",np.argmax(final_policy,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[3.84079131 4.42944661 5.25532944 5.7898373 ]
 [4.23698361 5.0311316  6.17753204 7.09227767]
 [4.58679918 0.         7.51917289 8.89373677]
 [5.47162292 6.85608655 8.60572239 0.        ]]
[Max] Action to State-value
 [[ 3.98806845  4.70791473  5.5894744   6.36240852]
 [ 4.53949648  5.57915034  6.8597634   7.97790285]
 [ 5.2114053   0.          8.08063796 10.        ]
 [ 6.13535129  7.50291206 10.          0.        ]]
Policy
 [[1 1 2 2]
 [1 1 2 2]
 [2 0 1 2]
 [1 1 1 0]]


# model-free Control Sarsa(lambda) (Q-learning)

In [16]:
rl.MF.iteration(n_episode = 1000,  model = "TD_lambda", control = True, on_policy = True)

The model is TD_lambda


In [17]:
Avalue = rl.MF.Avalue
final_policy = rl.MF.policy
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("Policy\n",np.argmax(final_policy,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[4.43114744 4.07349403 5.94738645 6.72567215]
 [4.8200256  5.11001168 6.58105458 7.33392263]
 [5.48297897 0.         8.31053186 8.66167549]
 [6.20189836 7.6188342  9.16067796 0.        ]]
[Max] Action to State-value
 [[ 4.78342161  4.17920904  6.29895301  7.67311587]
 [ 5.40965105  5.82082145  6.96636495  7.947906  ]
 [ 6.02885199  0.          8.98376845 10.        ]
 [ 6.6259179   7.99890536 10.          0.        ]]
Policy
 [[2 1 2 2]
 [2 1 1 2]
 [2 0 1 2]
 [1 0 1 0]]


# testing field

In [18]:
import time
a = np.array([1,2,3,4,5])

In [19]:
# t = time.time()
np.logspace(start=1,stop=len(a),num=len(a),endpoint=True,base=2)/2
# print(time.time()-t)

array([ 1.,  2.,  4.,  8., 16.])

In [20]:
# t = time.time()
np.array([2**i for i in range(len(a))])
# print(time.time()-t)

array([ 1,  2,  4,  8, 16])