In [1]:
import os
from maze_env import Maze
from utility import RL
from RL_control import DeepQNetwork
import time
import numpy as np

In [2]:
# def onKeyPress(event):
#     is_terminate = False
#     if (event.char == "w"):
#         is_terminate, reward = env.take_action(0, show_animate=True)
#     elif (event.char == "d"):
#         is_terminate, reward = env.take_action(1, show_animate=True)
#     elif (event.char == "s"):
#         is_terminate, reward = env.take_action(2, show_animate=True)
#     elif (event.char == "a"):
#         is_terminate, reward = env.take_action(3, show_animate=True)
#     elif (event.char == "q"):
#         env.destroy()
#     if (is_terminate):
#         env.reset()

In [3]:
# if __name__ == "__main__":
env = Maze()
rl = RL(env)
print('{0}x{1}, act_space = {2}'.format(env.MAZE_Limit[0],env.MAZE_Limit[1], len(env.action_space)))
# env.bind('<KeyPress>', onKeyPress)
# env.mainloop()

4x4, act_space = 4


# DP Prediction

In [4]:
rl.DP.iteration(update = 10)

9 [[ 0. -1. -2. -3.]
 [-1. -2.  0. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]


# model-free MC

In [5]:
rl.MF.iteration(n_episode = 3000,  model = "MC")

The model is MC


In [6]:
Avalue = rl.MF.Avalue
final_policy = rl.MF.policy
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[0],env.MAZE_Limit[1]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[0],env.MAZE_Limit[1]))

[Expect] State-value
 [[ 0.         -5.20420479 -7.01868919 -7.52032503]
 [-5.13818873 -6.25287097  0.         -7.19502524]
 [-6.98408265 -6.94825781 -6.26065077 -5.19816851]
 [-7.50945651 -7.00552472 -5.08479278  0.        ]]
[Max] Action to State-value
 [[ 0.         -1.         -5.75754682 -7.1063444 ]
 [-1.         -5.42449402  0.         -5.79526423]
 [-5.71122675 -6.56020825 -5.46707899 -1.        ]
 [-7.14422829 -5.55900961 -1.          0.        ]]


# model-free TD(0)

In [7]:
#hyper parameters
rl.MF.gamma = 0.9 # discount factor
rl.MF.lamb = 0.9 # parameter of sarsa
rl.MF.alpha = 0.5 # step size

In [8]:
rl.MF.iteration(n_episode = 3000,  model = "TD_0")

The model is TD_0


In [9]:
Avalue = rl.MF.Avalue
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[ 0.         -4.44343194 -7.7653562  -8.30400122]
 [-5.05419457 -5.60130001  0.         -7.27974744]
 [-6.37378648 -6.85965699 -5.2636192  -6.17026273]
 [-7.61081033 -6.37501865 -5.28514332  0.        ]]
[Max] Action to State-value
 [[ 0.         -1.         -6.77619063 -7.63120865]
 [-1.         -4.19153775  0.         -4.76980564]
 [-2.94873434 -6.00407332 -3.31299486 -1.        ]
 [-7.11771024 -4.07053033 -1.          0.        ]]


# model-free TD(n)

In [10]:
rl.MF.iteration(n_episode = 3000,  model = "TD_n")

The model is TD_n


In [11]:
Avalue = rl.MF.Avalue
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[ 0.         -3.75487437 -5.96489609 -7.41857246]
 [-4.37537882 -6.00092508  0.         -6.78123281]
 [-6.08546948 -6.25416345 -5.96758898 -4.60258688]
 [-8.19986119 -7.38832561 -5.54994619  0.        ]]
[Max] Action to State-value
 [[ 0.         -1.         -3.85543615 -6.63699061]
 [-1.         -3.92881665  0.         -6.23330791]
 [-3.05180604 -5.15777862 -4.79715167 -1.        ]
 [-7.11870367 -6.08874361 -1.          0.        ]]


# model-free TD(lambda)

In [12]:
rl.MF.iteration(n_episode = 1000,  model = "TD_lambda")

The model is TD_lambda


In [13]:
Avalue = rl.MF.Avalue
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[ 0.         -5.94479937 -6.70113288 -7.15159729]
 [-5.03796453 -6.273026    0.         -4.95964602]
 [-8.25236142 -6.78051515 -5.19864859 -4.41129735]
 [-8.66545659 -7.57850982 -5.00955175  0.        ]]
[Max] Action to State-value
 [[ 0.         -1.         -5.06286602 -6.56322458]
 [-1.         -3.94060371  0.         -3.88573462]
 [-7.67062149 -4.07904985 -2.33618171 -1.        ]
 [-8.24883766 -6.25042731 -1.          0.        ]]


# model-free Control MC

In [14]:
rl.MF.iteration(n_episode = 3000,  model = "MC", control = True)

The model is MC


In [15]:
Avalue = rl.MF.Avalue
final_policy = rl.MF.policy
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("Policy\n",np.argmax(final_policy,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[ 0.         -1.96949322 -3.4829283  -4.65396878]
 [-1.94120169 -3.09467254  0.         -3.36864278]
 [-3.33318475 -3.85356214 -3.12975857 -1.90335529]
 [-4.20162906 -3.3457591  -1.95654087  0.        ]]
[Max] Action to State-value
 [[ 0.         -1.         -2.78740907 -4.092357  ]
 [-1.         -2.74750745  0.         -2.68337168]
 [-2.63797238 -3.79768777 -2.78755798 -1.        ]
 [-3.93036833 -2.72540429 -1.          0.        ]]
Policy
 [[0 3 3 3]
 [0 3 0 2]
 [0 0 1 2]
 [1 1 1 0]]


# model-free Control Sarsa(lambda) (Q-learning)

In [16]:
rl.MF.iteration(n_episode = 30000,  model = "TD_lambda", control = True, on_policy = True)

The model is TD_lambda


In [17]:
Avalue = rl.MF.Avalue
final_policy = rl.MF.policy
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("Policy\n",np.argmax(final_policy,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[ 0.         -1.85065915 -3.76117155 -3.65755408]
 [-1.91980625 -3.20157548  0.         -3.41873487]
 [-3.84179095 -5.26992457 -4.02811553 -1.86745719]
 [-5.67116843 -4.02588911 -2.39803986  0.        ]]
[Max] Action to State-value
 [[ 0.         -1.         -2.45462739 -3.07650438]
 [-1.         -2.52488652  0.         -2.07477999]
 [-2.54262205 -5.08229124 -3.54156819 -1.        ]
 [-5.33139205 -3.17478601 -1.          0.        ]]
Policy
 [[0 3 3 2]
 [0 3 0 2]
 [0 2 1 2]
 [0 1 1 0]]


# testing field

In [18]:
import time
a = np.array([1,2,3,4,5])

In [19]:
# t = time.time()
np.logspace(start=1,stop=len(a),num=len(a),endpoint=True,base=2)/2
# print(time.time()-t)

array([ 1.,  2.,  4.,  8., 16.])

In [20]:
# t = time.time()
np.array([2**i for i in range(len(a))])
# print(time.time()-t)

array([ 1,  2,  4,  8, 16])