In [1]:
import os
from maze_env import Maze
from rl_algo import RL
import time
import numpy as np

In [2]:
# def onKeyPress(event):
#     is_terminate = False
#     if (event.char == "w"):
#         is_terminate, reward = env.take_action(0, show_animate=True)
#     elif (event.char == "d"):
#         is_terminate, reward = env.take_action(1, show_animate=True)
#     elif (event.char == "s"):
#         is_terminate, reward = env.take_action(2, show_animate=True)
#     elif (event.char == "a"):
#         is_terminate, reward = env.take_action(3, show_animate=True)
#     elif (event.char == "q"):
#         env.destroy()
#     if (is_terminate):
#         env.reset()

In [3]:
# if __name__ == "__main__":
env = Maze()
rl = RL(env)
print('{0}x{1}, act_space = {2}'.format(env.MAZE_Limit[0],env.MAZE_Limit[1], len(env.action_space)))
# env.bind('<KeyPress>', onKeyPress)
# env.mainloop()

4x4, act_space = 4


# DP Prediction

In [4]:
rl.DP.iteration(update = 10)

9 [[ 0.         -6.13796997 -8.35235596 -8.96731567]
 [-6.13796997 -7.73739624 -8.42782593 -8.35235596]
 [-8.35235596 -8.42782593 -7.73739624 -6.13796997]
 [-8.96731567 -8.35235596 -6.13796997  0.        ]]


# model-free MC

In [5]:
rl.MF.iteration(n_episode = 10000,  model = "MC")

The model is MC


In [6]:
Avalue = rl.MF.Avalue
final_policy = rl.MF.policy
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[0],env.MAZE_Limit[1]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[0],env.MAZE_Limit[1]))

[Expect] State-value
 [[ 0.         -5.24646479 -7.0871772  -7.62785631]
 [-5.29239044 -6.56155572 -7.22713229 -7.18856686]
 [-7.1552333  -7.3021403  -6.7505523  -5.394601  ]
 [-7.64295967 -7.09647788 -5.39378966  0.        ]]
[Max] Action to State-value
 [[ 0.         -1.         -5.61660451 -7.39513822]
 [-1.         -5.60056006 -6.97048746 -5.97446889]
 [-5.87177127 -6.95527475 -5.96531714 -1.        ]
 [-7.33254942 -5.63556616 -1.          0.        ]]


# model-free TD(0)

In [7]:
#hyper parameters
rl.MF.gamma = 0.9 # discount factor
rl.MF.lamb = 0.9 # parameter of sarsa
rl.MF.alpha = 0.5 # step size

In [8]:
rl.MF.iteration(n_episode = 3000,  model = "TD_0")

The model is TD_0


In [9]:
Avalue = rl.MF.Avalue
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[ 0.         -4.80102453 -6.7056914  -7.70408986]
 [-5.64369624 -5.98723472 -6.93271219 -6.37670319]
 [-7.41974104 -5.74400371 -6.41147944 -5.21596972]
 [-7.15405123 -6.20877077 -4.49174518  0.        ]]
[Max] Action to State-value
 [[ 0.         -1.         -5.45906085 -7.21492731]
 [-1.         -4.17447836 -5.9103544  -4.45704291]
 [-6.28357657 -5.22819742 -4.36292643 -1.        ]
 [-5.98782565 -4.93479369 -1.          0.        ]]


# model-free TD(n)

In [10]:
rl.MF.iteration(n_episode = 3000,  model = "TD_n")

The model is TD_n


In [11]:
Avalue = rl.MF.Avalue
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[ 0.         -5.69544991 -6.45025642 -7.27810396]
 [-4.56760864 -6.85018671 -7.09248196 -6.11351027]
 [-7.57839665 -6.82907906 -5.36809377 -4.07809917]
 [-6.65534063 -6.18962201 -5.0468156   0.        ]]
[Max] Action to State-value
 [[ 0.         -1.         -4.57289185 -6.32054406]
 [-1.         -4.44142465 -4.54129153 -3.97872722]
 [-6.26969615 -4.65925913 -3.52315403 -1.        ]
 [-4.56017177 -5.13775811 -1.          0.        ]]


# model-free TD(lambda)

In [12]:
rl.MF.iteration(n_episode = 1000,  model = "TD_lambda")

The model is TD_lambda


In [13]:
Avalue = rl.MF.Avalue
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[ 0.         -4.92376575 -7.9851775  -9.02248385]
 [-4.6368055  -6.08881458 -7.56293002 -7.20709493]
 [-7.52846959 -5.56751023 -5.18571042 -5.62261753]
 [-7.18128393 -4.96336066 -4.98836898  0.        ]]
[Max] Action to State-value
 [[ 0.         -1.         -5.24391312 -8.81504311]
 [-1.         -4.58781474 -7.00507526 -5.27691819]
 [-6.14624841 -5.16029347 -2.50664813 -1.        ]
 [-5.98011812 -2.01803151 -1.          0.        ]]


# model-free Control MC

In [14]:
rl.MF.iteration(n_episode = 1000,  model = "MC", control = True)

The model is MC


In [15]:
Avalue = rl.MF.Avalue
final_policy = rl.MF.policy
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("Policy\n",np.argmax(final_policy,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[ 0.         -1.9535709  -3.49034733 -4.59995441]
 [-2.05553835 -3.26318374 -4.08023502 -3.78413935]
 [-3.71834354 -4.05114318 -3.31674566 -2.15035378]
 [-4.93585946 -3.59006203 -2.06940903  0.        ]]
[Max] Action to State-value
 [[ 0.         -1.         -2.79636872 -4.3032705 ]
 [-1.         -2.75411091 -3.91051946 -2.90581575]
 [-2.91987272 -3.868522   -2.75367413 -1.        ]
 [-4.29678726 -2.81103894 -1.          0.        ]]
Policy
 [[0 3 3 3]
 [0 0 2 2]
 [0 0 2 2]
 [1 1 1 0]]


# model-free Control Sarsa(lambda) (Q-learning)

In [16]:
rl.MF.iteration(n_episode = 1000,  model = "TD_lambda", control = True, on_policy = True)

The model is TD_lambda


In [17]:
Avalue = rl.MF.Avalue
final_policy = rl.MF.policy
print("[Expect] State-value\n",np.sum(final_policy*Avalue, axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("[Max] Action to State-value\n",np.max(Avalue,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))
print("Policy\n",np.argmax(final_policy,axis=0).reshape(env.MAZE_Limit[1],env.MAZE_Limit[0]))

[Expect] State-value
 [[ 0.         -2.02524199 -2.72496139 -4.37597647]
 [-2.1628405  -3.22611902 -3.68792996 -3.35872205]
 [-3.15843345 -3.7737247  -2.97198865 -1.87717893]
 [-4.81644061 -3.05562758 -2.07882591  0.        ]]
[Max] Action to State-value
 [[ 0.         -1.         -1.97413842 -3.43595983]
 [-1.         -2.48687192 -2.99846897 -2.64736597]
 [-2.46428569 -3.5438301  -2.45066892 -1.        ]
 [-4.65416695 -2.30903646 -1.          0.        ]]
Policy
 [[0 3 0 2]
 [0 0 3 2]
 [0 3 1 2]
 [3 1 1 0]]


# testing field

In [18]:
import time
a = np.array([1,2,3,4,5])

In [19]:
# t = time.time()
np.logspace(start=1,stop=len(a),num=len(a),endpoint=True,base=2)/2
# print(time.time()-t)

array([ 1.,  2.,  4.,  8., 16.])

In [20]:
# t = time.time()
np.array([2**i for i in range(len(a))])
# print(time.time()-t)

array([ 1,  2,  4,  8, 16])