In [1]:
import os
from maze_env import Maze
from utility import Prediction
import time

In [2]:
# def onKeyPress(event):
#     is_terminate = False
#     if (event.char == "w"):
#         is_terminate, reward = env.take_action(0, show_animate=True)
#     elif (event.char == "d"):
#         is_terminate, reward = env.take_action(1, show_animate=True)
#     elif (event.char == "s"):
#         is_terminate, reward = env.take_action(2, show_animate=True)
#     elif (event.char == "a"):
#         is_terminate, reward = env.take_action(3, show_animate=True)
#     elif (event.char == "q"):
#         env.destroy()
#     if (is_terminate):
#         env.reset()

In [3]:
# if __name__ == "__main__":
env = Maze()
prd = Prediction(env)
print('{0}x{1}, act_space = {2}'.format(env.MAZE_Limit[0],env.MAZE_Limit[1], len(env.action_space)))
# env.bind('<KeyPress>', onKeyPress)
# env.mainloop()

4x4, act_space = 4


# DP Prediction

In [4]:
prd.DP.iteration(update = 10)

9 [[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]


# model-free MC

In [5]:
prd.MF.iteration(n_episode = 3000,  model = "MC")

The model is MC
V
 [[ 0.         -5.30296321 -7.14809233 -7.70766931]
 [-5.37328533 -6.54697    -7.21460366 -7.20971614]
 [-7.1802325  -7.23737396 -6.67141536 -5.36627636]
 [-7.63923643 -7.14747145 -5.38532296  0.        ]]
--------------------------



# model-free TD(0)

In [6]:
prd.MF.iteration(n_episode = 3000,  model = "TD_0")

The model is TD_0
V
 [[ 0.         -5.43471276 -7.52501688 -7.33972808]
 [-6.66460096 -6.11813154 -6.22089998 -6.70814091]
 [-7.20371921 -6.08747798 -6.1011278  -5.82899724]
 [-8.25254808 -7.86802782 -3.79229808  0.        ]]
--------------------------



# model-free TD(n)

In [7]:
prd.MF.iteration(n_episode = 3000,  model = "TD_n")

The model is TD_n
V
 [[ 0.         -4.69817329 -8.13295462 -8.54681032]
 [-5.28216535 -5.27566057 -6.46700876 -7.73915091]
 [-8.5347789  -5.61991346 -6.11345997 -2.06812383]
 [-8.26354858 -7.31064434 -7.19959414  0.        ]]
--------------------------



# model-free TD(lambda)

In [8]:
prd.MF.iteration(n_episode = 3000,  model = "TD_lambda")

The model is TD_lambda
V
 [[ 0.         -2.06091607 -3.73210289 -5.50287846]
 [-3.52916964 -4.81006725 -3.85567505 -4.45415936]
 [-5.90619846 -5.53232855 -6.04847078 -3.29086027]
 [-0.1534397  -3.21163778 -3.87434012  0.        ]]
--------------------------



# testing field

In [9]:
import numpy as np
a = np.array([1,2,3,4,5])

In [10]:
np.logspace(start=1,stop=len(a),num=len(a),endpoint=True,base=2)/2

array([ 1.,  2.,  4.,  8., 16.])